image: node:8

stages:
  - test
  - build
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
   - npm test
  artifacts:
    paths:
      - coverage/
  
build:
  stage: build
  image: docker:latest
  only:
    - development
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME} --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"
  after_script:
    - "docker logout ${CI_REGISTRY}"

publish-coverage:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Ensure that the ssh is known
    - ssh-keyscan $BEEFBOARD_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - if [[ "$CI_COMMIT_REF_NAME"=="development" ]]; then
        SERVICE="web_beefboard-test-images";
      else
        SERVICE="web_beefboard-images";
      fi
    - command="docker service update ${SERVICE} --image ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME} --with-registry-auth"
    - echo $command
    - ssh $DEPLOY_USER@$BEEFBOARD_HOST "$command"
  only:
    - master
    - development
